#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Input file for 3dinversion.py — GTI interseismic inversion.

Defaults (set in 3dinversion.py, no need to repeat here):
  smoothing='yes', lambda1=1., constraint='yes'
  base='yes', orb='yes', mogi='no'
  xini=None, bndmin=[], bndmax=[]
  normodel=[1., 1., 500., 1., 1., 1., 1.]
  xlim/ylim/zlim: auto-derived from InSAR data extent
  coplot/displot/timeplot/residual/plotlos='no', insarplot/faultplot='yes'
"""

import os
try:
    from inversfault import fault
    from inverskernel import interseismic
    from inversnetwork import insarstack
    from readgmt import gmt
except ImportError:
    pass   # imported by the parent script

# ======================================================================================================================
# Paths
# ======================================================================================================================

maindir   = '/Users/simon/scratch/dev_fold/work/data/'
outputdir = '/Users/simon/scratch/dev_fold/work/gti/output/'
os.makedirs(outputdir, exist_ok=True)

# ======================================================================================================================
# Model: kernels + fault
# ======================================================================================================================

kernels = [
    interseismic(name='interseismic', date=0., inversion='kernel', sigmam=1.),
]

flt = fault(
    name='ramp',
    wdir=maindir + 'faults/',
     model=['ramp-flat.flt'],   # generated by: python3 GTI/seg2flt.py work/gti/ramp_seg.flt > work/data/faults/ramp.flt
 )
#     model=['ramp.flt'],   # generated by: python3 GTI/seg2flt.py work/gti/ramp_seg.flt > work/data/faults/ramp.flt
# )
#     model=['flower2d.flt'],   # generated by: python3 GTI/seg2flt.py work/gti/ramp_seg.flt > work/data/faults/ramp.flt
# )

# ======================================================================================================================
# InSAR data
# ======================================================================================================================
# Files: x(km)  y(km)  los(mm)  [inc_angle  [head_angle]]
#
# Projection options (choose one per network):
#   av_los + av_heading : constant incidence/heading angles for all pixels
#                         inc = 0° → vertical,  inc = 90° → horizontal
#   los=True            : read incidence angle per pixel from column 4
#   head=True           : read heading angle per pixel from column 5 (requires los=True or av_los)

insar = [
    insarstack(
        network='vertical_2003-2019_mm_crop03_no2004_km.xylos',
        wdir=maindir + 'insar/decomp2026/',
        tmin=0., tmax=1.,
        av_los=0., av_heading=0.,    # vertical component (decomposition already done)
        errorfile = 'sig_vertical_2003-2019_mm_crop03_no2004_km.xylos',
        samp=4,
    ),
    insarstack(
        network='shortening_2003-2019_mm_crop03_no2004_km.xylos',
        wdir=maindir + 'insar/decomp2026/',
        tmin=0., tmax=1.,
        av_los=-90., av_heading=22., # horizontal shortening (decomposition already done)
        errorfile = 'sig_shortening_2003-2019_mm_crop03_no2004_km.xylos',
        samp=4,
    ),
    # Example for real InSAR with per-pixel geometry:
    # insarstack(
    #     network='asc_envisat.xylos',      # cols: x y los inc heading
    #     wdir=maindir + 'insar/',
    #     tmin=2003., tmax=2010.,
    #     los=True, head=True,
    #     samp=5,
    # ),
]

# ======================================================================================================================
# Test options
# ======================================================================================================================

plot_data = 'yes'  # display InSAR data + fault model before inversion

# ======================================================================================================================
# Profile (optional — used if profileplot='yes')
# ======================================================================================================================
# Profile perpendicular to fault strike; same geometry as flower2d profile.
#   x, y    : profile origin (Easting, Northing) in km
#   strike  : fault strike (° N-CW); profile is perpendicular to this
#   l       : total profile length (km) — data shown from -l/2 to +l/2
#   w       : selection half-width along strike (km)
#   lbins   : bin size along profile (km)

profile = dict(
    name   = 'post03',
    x      = 46.5,    # km Easting
    y      = -17.,    # km Northing
    strike = -70.,    # ° (fault strike)
    l      = 70.,     # km half-length
    w      = 2.,     # km half-width along strike for selection
    lbins  = 2.,      # km bin size
)

profileplot = 'yes'

# ======================================================================================================================
# Optional overrides (uncomment to use)
# ======================================================================================================================

lambda1 = .1          # Laplacian smoothing weight
normodel = [1., 1., 500., 1., 1., 1., 1.]
# gps, glissement sur les patches, rampes InSAR, model2d, ref, mogi, edge
import numpy as np
bndmin = [-np.inf, 0.,   -np.inf, -np.inf, -np.inf, -np.inf, -np.inf]
bndmax = [ np.inf, 500, np.inf,   np.inf,   np.inf,  np.inf,  np.inf]

# xlim = [-280, -60]    # km — auto-derived from data if not set
# ylim = [  -60, 220]
# zlim = [  -30,   0]

# ======================================================================================================================
# GMT overlay files (optional)
# ======================================================================================================================

gmtfiles = [
    gmt(name='Fault traces', wdir=maindir+'faults/', filename='fault_mathieu_deg_km.gmt', color='black', width=1.),
]
